openapi: 3.0.1
info:
  title: bibapi
  description: bibapi
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: bibapi
    description: bibapi endpoints
  - name: Specification
    description: The swagger API specification
paths:
  /bibapi/predict/{nameFragment}:
    get:
      tags:
        - Examples
      parameters:
        - in: path
          name: nameFragment
          description: Fragment of name to predict
          required: true
          schema:
            type: string
      responses:
        200:
          description: Return a json array of possible names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                $ref: '#/components/schemas/Example'
        4XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
components:
  schemas:
    Example:
      type: object
      properties:
        id:
          type: integer
          example: 3
        name:
          type: string
          example: example 3
    Error:
      type: object
      additionalProperties: true

    ExampleBody:
      title: example
      required:
        - name
      type: object
      properties:
        name:
          type: string
          example: no_stress
